version: '3.11'
services:
    core_api:
        build: .
        container_name: "trains_2024_server"
        ports:
            - "8000:8000"
            - "5858:5858"
        volumes:
            - ./app:/app